/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'john.lopez' at '23/11/15 02:57 PM' with Gradle 2.6
 *
 * @author john.lopez, @date 23/11/15 02:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
